In [39]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

### Store CSV into DataFrame

In [40]:
csv_file = "Raw_Data/geo_data/winery-lat-lng-final.csv"
winery_geo_df = pd.read_csv(csv_file)
winery_geo_df.head(100)

                      winery   latitude   longitude
0                    Nicosia  35.185566   33.382276
1        Quinta dos Avidagos  41.387690   -7.276865
2                  Rainstorm  40.089829  -88.248177
3                 St. Julian  40.015971 -105.282767
4               Sweet Cheeks  42.343904  -71.101100
5                     Tandem  36.358159  -94.213735
6            Terre di Giurfo  37.111291   14.632700
7                   Trimbach  48.194905    7.326016
8         Jean-Baptiste Adam  48.126568    7.283714
9         Kirkland Signature  47.681243 -122.181894
10                Leon Beyer  48.042547    7.306562
11          Louis M. Martini  38.491074 -122.452179
12       Masseria Setteporte  38.909701  -76.999219
13                  Mirassou  25.943284  -80.296723
14           Richard Böcking  49.947177    7.112136
15                  Pradorey  41.703093   -3.790284
16               Quiévremont  49.703758    0.759117
17                   Acrobat  30.243192  -97.736861
18        Baglio di Pianetto  37.988126   13.349254
19                   Bianchi  37.654419 -122.141173
20                 Canicattì  37.358178   13.850690
21       Castello di Amorosa  38.558417 -122.542601
22   Clarksburg Wine Company  38.422495 -121.532457
23      Domaine de la Madone  46.197634    4.684787
24                   Envolve  27.994282  -82.546990
25                     Erath  29.958261  -92.035956
26                   Estampa  34.238601 -118.571543
27       Feudi del Pisciotto  37.115450   14.411940
28      Feudi di San Marzano  40.460951   17.496714
29             Feudo Montoni  38.148438   13.336047
..                       ...        ...         ...
70                  Palencia  30.026159  -81.385626
71             Poggio Alloro  43.487718   11.065163
72            Fattoria Sardi  43.876385   10.503534
73            Ferrari-Carano  38.711393 -122.978297
74              Folie à Deux  38.421283 -122.390024
75                Franciscan  36.088094  -95.785133
76                     Fuchs  39.061514  -94.784029
77                      Gård  46.995032 -120.547456
78                Heron Hill  42.449624  -77.201392
79          Soquel Vineyards  37.029516 -121.933867
80                   Ventosa  42.857164  -76.936131
81         Lamoreaux Landing  42.576632  -76.858453
82                     Leyda -33.613157  -71.450184
83         Marchesi Antinori  38.433166 -122.289791
84  Marchesi de' Frescobaldi  40.905533  -74.402750
85              Martin Ranch  37.040295 -121.711400
86                 Ornellaia  38.225892 -122.263705
87            Pardon et Fils  46.147659    4.598066
88                      Piña  38.467140 -122.377318
89              Podere Ciona  43.476413   11.456984
90             Poggioventoso  42.906522   10.968290
91                      Pull  36.220953  -95.877007
92                        R2  27.967495  -82.751513
93                    Rideau  45.425161  -75.691270
94            Tenuta Forconi  43.696166   10.989761
95             Dopff & Irion  48.166199    7.304255
96                   Ceretto  32.776382 -117.060575
97                    Matrix  36.096837  -95.918729
98                 Mauritson  38.650488 -122.912031
99   Henry's Drive Vignerons -34.982414  138.733575

[100 rows x 3 columns]

### Connect to local database

In [41]:
conn_string = "mysql://root:FlyFly99!@localhost:3306/winery_db"
engine = create_engine(conn_string)

### Check for tables

In [42]:
engine.table_names()

['coordinates']

In [43]:
# winery_geo_df.loc[winery_geo_df['winery'] == "St. Julian"]
winery_geo_df.loc[3039]
# winery_geo_df.dtypes

winery       Milijan Jelić
latitude           44.2531
longitude          19.9074
Name: 3039, dtype: object

In [44]:
winery_geo_df["winery"] = winery_geo_df["winery"].apply(lambda x: x.encode("utf8"))

### Use pandas to load csv converted DataFrame into database

In [35]:
winery_geo_df.to_sql(name='coordinates', con=engine, if_exists='append', index=False)

### Confirm data has been added by querying the customer_name table
* NOTE: can also check using pgAdmin

In [38]:
pd.read_sql_query('select * from coordinates', con=engine).head()

   ID               winery   latitude   longitude
0   1              Nicosia  35.185566   33.382276
1   2  Quinta dos Avidagos  41.387690   -7.276865
2   3            Rainstorm  40.089829  -88.248177
3   4           St. Julian  40.015971 -105.282767
4   5         Sweet Cheeks  42.343904  -71.101100